version: "3.6"
services:
    php-apache:
        image: registry.gitlab.com/andersonpem/apache-php-zsh:7.4
# Use Platform selection if you're running on a Mac
#        platform: linux/amd64
        restart: always
        volumes:
            - ./code:/var/www/html
        ports:
            - 80:80

        environment:
            #General settings
            #Ext enable
            PHP_EXTENSIONS: ${PHP_EXTENSIONS}
            TZ: ${TZ}
            TEMPLATE_PHP_INI: ${TEMPLATE_PHP_INI}

            #PHP.ini settings
            PHP_INI_UPLOAD_MAX_FILESIZE: ${PHP_INI_UPLOAD_MAX_FILESIZE}
            PHP_INI_MAX_EXECUTION_TIME: ${PHP_INI_MAX_EXECUTION_TIME}
            PHP_INI_MEMORY_LIMIT: ${PHP_INI_MEMORY_LIMIT}
            PHP_INI_DISPLAY_ERRORS: ${PHP_INI_DISPLAY_ERRORS}
            PHP_INI_DATE__TIMEZONE: ${TZ}
            PHP_INI_SHORT_OPEN_TAG: ${PHP_INI_SHORT_OPEN_TAG}
            APACHE_DOCUMENT_ROOT: ${DOCUMENT_ROOT}
            #Debug only
            PHP_EXTENSION_XDEBUG: ${PHP_EXTENSION_XDEBUG}
            PHP_INI_XDEBUG__XDEBUG_MODE: ${XDEBUG_MODE}
            PHP_INI_XDEBUG__XDEBUG_CONNECT_TIMEOUT_MS: ${XDEBUG_CONNECT_TIMEOUT_MS}
            PHP_INI_XDEBUG__START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
            PHP_INI_XDEBUG__CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
            PHP_INI_XDEBUG__CLIENT_PORT: ${PHP_INI_XDEBUG__CLIENT_PORT}
            PHP_INI_XDEBUG__REMOTE_HANDLER: "dbgp"
            PHP_INI_XDEBUG__IDEKEY: ${PHP_INI_XDEBUG__IDEKEY}
            # PHP_INI_XDEBUG__REMOTE_LOG: "xdebug.log"
            PHP_INI_ERROR_REPORTING: ${PHP_INI_ERROR_REPORTING}
            #Production Settings
            # TEMPLATE_PHP_INI: production
            DOCKER_USER: ${DOCKER_USER}
            APACHE_RUN_USER: ${APACHE_RUN_USER}
            APACHE_RUN_GROUP: ${APACHE_RUN_GROUP}
    cron:
        image: registry.gitlab.com/andersonpem/apache-php-zsh:cron-1.0  

    mysql:
        image: mariadb
        restart: unless-stopped
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql:delegated
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - ${TZ}
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080

 
